---
title: "Python Demo"
author: "Justin Huebner"
date: "2/8/2020"
output: 
  html_document:
    code_folding: show
    csl: biomed-central.csl
    df_print: paged
    fig_caption: yes
    fig_height: 6
    fig_width: 7
    theme: journal
    toc: yes
    toc_float: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::knit_engines$set(python = reticulate::eng_python)
```

## R Markdown

```{r}
library(reticulate)
library(crosstalk)
input=read.csv("solarData/inputData.csv", header = T)
target=read.csv("solarData/exampleData.csv")

sd = SharedData$new(input)

crosstalk::filter_select("station","Select County:",sd,group="STID",)

output=input[c(-26:-17)]
output=output[c(-18:-21)]
output=output[c(-25:-26)]
output=output[-1:-3]

#need to change -996 to 0's

```

```{python}
import numpy
import sklearn as sk
from sklearn.neural_network import MLPRegressor

import joblib

# read the file
readFile = open("solarData/exampleData.csv", "r")

# remove columns 5 and 13, and convert remainders to floats
# also convert the last column to 1 or 0
rows = (line.split(',') for line in readFile)
x = list(rows)

x.pop(0)

# convert to floats
for i in range(len(x)):
    for j in range(len(x[i])):
        x[i][j] = float(x[i][j])

x = numpy.array(x)

#compute standard deviations and means
means = numpy.mean(x, axis=0)
stddev = numpy.std(x, axis=0)


#normalize training data
for i in range(len(x)):
    for j in range(len(x[i])):
        x[i][j] = (x[i][j] - means[j]) / stddev[j]

filename = 'finalNN.sav'
mlp = joblib.load(filename)

x = numpy.nan_to_num(x)

pred = mlp.predict(x)
print(numpy.average(pred))
```